name: Run java test
run-name: java_test
on: workflow_dispatch
jobs:
  Run-java:
    runs-on: ubuntu-latest
    steps:
      - name: Java Run
        uses: actions/checkout@v5
      - run: chmod +x ./.github/workflows/script/*
      - run: ./.github/workflows/script/configure-cpolar.sh
      - run: cd ${{ github.workspace }}

      - run: git clone https://github.com/yuye2nd/mc-file.git
      - run: ls
      - run: wget -P mc-file https://fill-data.papermc.io/v1/objects/b0d55be3ba19cb6e040f0e7fba400e5224a271fbc7db73a9683aef7468425af9/folia-1.20.4-31.jar
      - run: ls mc-file
      - run: java --version
      - run: java -server -Xms1G -Xmx12G -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1HeapRegionSize=8M -XX:G1HeapWastePercent=5 -XX:G1MaxNewSizePercent=40 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1NewSizePercent=30 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -XX:MaxGCPauseMillis=200 -XX:MaxTenuringThreshold=1 -XX:SurvivorRatio=32 -jar folia-1.20.4-31.jar
      - run: ls mc-file
      - run: cd mc-file && git init
      - run: cd mc-file && git add .
      - run: cd mc-file && git config --global user.email "3607808291@qq.com"
      - run: cd mc-file && git config --global user.name "qeqenn"
      - run: cd mc-file && git commit -m "sync file"
      - run: cd mc-file && git branch -M main
      - run: cd mc-file && git remote add origin https://github.com/yuye2nd/mc-file.git
      - run: cd mc-file && git push -u origin main
