name: Run java test
run-name: java_test
on: workflow_dispatch
jobs:
  Run-java:
    runs-on: ubuntu-latest
    steps:
      - name: Java Run
        uses: actions/checkout@v5
      - run: chmod +x ./.github/workflows/script/*
      - run: ./.github/workflows/script/install-dep.sh
      - run: ./.github/workflows/script/configure-cpolar.sh
      - run: cd ${{ github.workspace }}

      
      - run: mkdir folia
      - run: cd folia
      - run: wget https://fill-data.papermc.io/v1/objects/f52c408490a0225611e67907a3ca19f7e6da2c6bc899e715d5f46844e7103c39/folia-1.21.11-14.jar
      - run: ls
      - run: java --version
      - run: java -server -Xms1G -Xmx12G -jar folia-1.21.11-14.jar
      - run: cd ..
      - run: git add .
      - run: git commit -m "Testing java runner"
      - run: git push
