name: Run java test
run-name: java_test
on: workflow_dispatch
jobs:
  Run-java:
    runs-on: ubuntu-latest
    steps:
      - name: Java Run
        uses: actions/checkout@v5
      - run: sudo ./.github/workflows/script/install-dep.sh
      - run: sudo ./.github/workflows/script/configure-cpolar.sh
      - run: sudo ./.github/workflows/script/runjava.sh
