name: qemu-img create 32g
run-name: Create 32g qcow2
on: workflow_dispatch
jobs:
  Create-img:
    runs-on: ubuntu-latest
    steps:
      - run: echo "start create img"
      - name: Create img
        uses: actions/checkout@v5
      - run: sudo apt update
      - run: sudo apt install qemu-utils qemu-system-x86 -y
      - run: qemu-img create ${{ github.workspace }}/new.qcow2 32G -f qcow2
      - run: echo "job create complete"
      - run: sudo curl -L https://www.cpolar.com/static/downloads/install-release-cpolar.sh | sudo bash
      - run: cpolar authtoken Y2ZmNWIxYzMtM2I3NS00NWU2LTg3MDctZDUyNTFmYTE2ZGY5
      - run: sudo systemctl enable cpolar
      - run: sudo systemctl start cpolar
      - run: cat /usr/local/etc/cpolar/cpolar.yml
