name: qemu-img create 32g
run-name: Create 32g qcow2
on: workflow_dispatch
jobs:
  Create-img:
    runs-on: ubuntu-latest
    steps:
      - run: echo "start create img"
      - name: Create img
        uses: actions/checkout@v5
      - run: sudo apt update
      - run: sudo apt install qemu-utils qemu-system-x86_64 -y
      - run: qemu-img create ${{ github.workspace }}/new.qcow2 32G -f qcow2
      - run: echo "job create complete"
      - run: wget https://www.cpolar.com/static/downloads/releases/3.3.18/cpolar-stable-linux-amd64.zip
      - run: unzip cpolar-stable-linux-amd64.zip
      - run: ./cpolar authtoken Y2ZmNWIxYzMtM2I3NS00NWU2LTg3MDctZDUyNTFmYTE2ZGY5
      - run: ls
      - run: ./cpolar tcp 1
      
